# Generated by Django 5.1.7 on 2025-04-21 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedistributionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tablet_name', models.CharField(max_length=100)),
                ('requested_quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('fulfilled', 'Fulfilled'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_sent', to='signup.medical_store_details')),
                ('to_clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_received', to='signup.medical_store_details')),
            ],
        ),
    ]
