# Generated by Django 5.1.6 on 2025-02-25 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Medicine",
            fields=[
                ("medicine_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("expiry_date", models.DateField()),
                ("quantity_available", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Purchase",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("purchase_date", models.DateField()),
                ("quantity_purchased", models.IntegerField()),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.medicine",
                    ),
                ),
            ],
        ),
    ]
