# Generated by Django 5.1.7 on 2025-03-30 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabletConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tablet_name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('week_1', models.IntegerField(default=0)),
                ('week_2', models.IntegerField(default=0)),
                ('week_3', models.IntegerField(default=0)),
                ('week_4', models.IntegerField(default=0)),
                ('week_5', models.IntegerField(default=0)),
                ('week_6', models.IntegerField(default=0)),
                ('week_7', models.IntegerField(default=0)),
                ('week_8', models.IntegerField(default=0)),
                ('week_9', models.IntegerField(default=0)),
                ('week_10', models.IntegerField(default=0)),
                ('week_11', models.IntegerField(default=0)),
                ('week_12', models.IntegerField(default=0)),
                ('week_13', models.IntegerField(default=0)),
                ('week_14', models.IntegerField(default=0)),
                ('week_15', models.IntegerField(default=0)),
                ('week_16', models.IntegerField(default=0)),
                ('week_17', models.IntegerField(default=0)),
                ('week_18', models.IntegerField(default=0)),
                ('week_19', models.IntegerField(default=0)),
                ('week_20', models.IntegerField(default=0)),
                ('week_21', models.IntegerField(default=0)),
                ('week_22', models.IntegerField(default=0)),
                ('week_23', models.IntegerField(default=0)),
                ('week_24', models.IntegerField(default=0)),
                ('week_25', models.IntegerField(default=0)),
                ('week_26', models.IntegerField(default=0)),
                ('week_27', models.IntegerField(default=0)),
                ('week_28', models.IntegerField(default=0)),
                ('week_29', models.IntegerField(default=0)),
                ('week_30', models.IntegerField(default=0)),
                ('week_31', models.IntegerField(default=0)),
                ('week_32', models.IntegerField(default=0)),
                ('week_33', models.IntegerField(default=0)),
                ('week_34', models.IntegerField(default=0)),
                ('week_35', models.IntegerField(default=0)),
                ('week_36', models.IntegerField(default=0)),
                ('week_37', models.IntegerField(default=0)),
                ('week_38', models.IntegerField(default=0)),
                ('week_39', models.IntegerField(default=0)),
                ('week_40', models.IntegerField(default=0)),
                ('week_41', models.IntegerField(default=0)),
                ('week_42', models.IntegerField(default=0)),
                ('week_43', models.IntegerField(default=0)),
                ('week_44', models.IntegerField(default=0)),
                ('week_45', models.IntegerField(default=0)),
                ('week_46', models.IntegerField(default=0)),
                ('week_47', models.IntegerField(default=0)),
                ('week_48', models.IntegerField(default=0)),
                ('week_49', models.IntegerField(default=0)),
                ('week_50', models.IntegerField(default=0)),
                ('week_51', models.IntegerField(default=0)),
                ('week_52', models.IntegerField(default=0)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumption_records', to='medicine.medicine')),
            ],
            options={
                'unique_together': {('clinic', 'tablet_name', 'year')},
            },
        ),
    ]
