# Generated by Django 5.1.7 on 2025-03-31 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
        ('tabletConsumption', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabletconsumption',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumption_records', to='signup.medical_store_details'),
        ),
    ]
